CREATE TABLE ORDER_DETAILS (ODER_ID VARCHAR(50),
UDER_ID VARCHAR(50),
VEHICLE_ID VARCHAR(50),
VEHICLE_TYPE VARCHAR(50),
P_WEIGHT VARCHAR(50),
FROM_CITY VARCHAR(50),
FROM_ADDRESS VARCHAR(50),
TO_CITY VARCHAR(50),
TO_ADDRESS VARCHAR(50),
INSURANCE_ID VARCHAR(50),
BOOKING_DATE DATE )

SELECT * FROM ORDER_DETAILS


DROP TABLE ORDER_DETAILS


